WebMyPham/WebMyPham/WebMyPham/WebMyPham/Areas/Admin/Controllers/SanPhamAdController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebMyPham.Models;
using System.Linq;

namespace WebMyPham.Areas.Admin.Controllers
{
    public class SanPhamAdController : Controller
    {
        private WebMyPhamContent db = new WebMyPhamContent();
        // GET: Admin/SanPhamAd
        public ActionResult Index()
        {
            var sanpham = db.SanPhams.Include(p => p.LoaiSanPham);
            return View(sanpham.ToList());
        }
        //Get:Admin/SanPhamad/Detail/5
        public ActionResult Details(string id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanpham = db.SanPhams.Find(id);
            if(sanpham == null)
            {
                return HttpNotFound();

            }
            return View(sanpham);
        }
        //Get;Admin/SanPhamAd/Create
        public ActionResult Create()
        {
            ViewBag.idsp = new SelectList(db.LoaiSanPhams, "idsp", "tensp");
            return View();

        }
        //Post:Admin/SanPhamAd/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create ([Bind(Include = "idsp,tensp,idloaisp,mota,giaban,soluong,giamgia,hinhanh,trangthai")] SanPham sanpham, HttpPostedFileBase Fileupload, HttpPostedFileBase Fileupload_2)
        {
            if(Fileupload == null)
            {
                ViewBag.ThongBao = "Yeu cau nhap lai hinh anh";
            }
            else
            {
                if(ModelState.IsValid)
                {
                    var filename = Path.GetFileName(Fileupload.FileName);
                    var path = Path.Combine(Server.MapPath("~/Images"), filename);
                   
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.ThongBao = "Hình Ảnh đã tồn tại";
                    }
                    else   
                    {
                        Fileupload.SaveAs(path);    
                    }
                  //  sanpham.idsp = "";
                    sanpham.hinhanh = filename;
                    db.SanPhams.Add(sanpham);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
              
            }
            ViewBag.idsp = new SelectList(db.LoaiSanPhams, "idsp", "tensp", sanpham.idsp);
            return View(sanpham);
        }
        //get:Admin/SanPhamAd/Edit/5
        public ActionResult Edit(string id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanpham = db.SanPhams.Find(id);
            if(sanpham == null)
            {
                return HttpNotFound();
            }
            ViewBag.idsp = new SelectList(db.LoaiSanPhams, "idsp", "tensp", sanpham.idsp);
            return View(sanpham);

        }
        //POST : Admin/SanPhamAd/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit ([Bind(Include ="idsp,tensp,idloaisp,mota,giaban,soluong,giamgia,hinhanh,trangthai")] SanPham sanpham)
        {
            if(ModelState.IsValid)
            {
                db.Entry(sanpham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idsp = new SelectList(db.LoaiSanPhams, "idsp", "tensp", sanpham.idsp);
            return View(sanpham);
        }
        //get: Admin/SanPhamAd/Delete/5
        public ActionResult Delete(string id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanpham = db.SanPhams.Find(id);
            if(sanpham == null)
            {
                return HttpNotFound();
            }
            return View(sanpham);
        }
        //Post : Admin/SanPhamAd/Delete/5
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed (string id)
        {
            SanPham sanpham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanpham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

WebMyPham/WebMyPham/WebMyPham/WebMyPham/Areas/Admin/Views/SanPhamAd/Create.cshtml
@model WebMyPham.Models.SanPham
@{
    ViewBag.Title = "Them san pham";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}

<style>
    .date-time {
        height: 29px;
    }

    p {
        text-align: center;
        font-weight: bold;
        font-size: 20px;
    }
</style>



@using (Html.BeginForm("Create", "SanPhamAd", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <br />
    <p>Thêm Mới Sản Phẩm</p>
    <div class="form-horizontal col-xl-9 col-lg-10 col-md-12 col-sm-12">
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.idsp, "Mã Sản Phẩm", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.idsp, new
           {
               htmlAttributes = new
               {
                   @class = "form-control",
                   @disabled = "true",
                   @placeholder = "Mã sản phẩm",
                   @maxlength = "100",
                   @name = "masp",
                   @type = "text",
                   @value = ""@*, @required = ""*@,
                   @id = "masp"
               }
           })
                @*@Html.ValidationMessageFor(model => model.MASP, "", new { @class = "text-danger" })*@
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.tensp, "Tên Sản Phẩm", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.tensp, new { htmlAttributes = new { @class = "form-control", @name = "title", @type = "text", @value = "", @id = "title", @placeholder = "Tên sản phẩm ( ~ 70 ký tự )", @required = "", @maxlength = "100" } })
                @Html.ValidationMessageFor(model => model.tensp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mota, "Mô Tả", htmlAttributes: new { @class = "col-sm-3 control-label" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.mota, new { htmlAttributes = new { @class = "form-control", @name = "keywords", @type = "text", @value = "", @id = "keywords", @placeholder = "Mô Tả ( ~ 160 ký tự )", @maxlength = "255" } })
                @Html.ValidationMessageFor(model => model.mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinhanh, "Hình Ảnh", htmlAttributes: new { @class = "col-sm-3 control-label" })
            <div class="col-sm-4">
                <input type="file" name="Fileupload" class="btn btn-primary" />
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.giaban, "Giá Sản Phẩm", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.giaban, new { htmlAttributes = new { @class = "form-control", @placeholder = "Giá sản phẩm (đơn vị: VNĐ)", @repuired = "", @maxlength = "255" } })
                @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
            </div>
        </div>

        

       

        <div class="form-group">
            @Html.LabelFor(model => model.trangthai, "Trạng Thái", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.trangthai, new { htmlAttributes = new { @class = "form-control", @placeholder = "Còn Hàng || Hết Hàng", @required = "" } })
                @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.soluong, "Số Lượng", htmlAttributes: new { @class = "col-sm-3 control-label" })
            <div class="col-sm-2">
                @Html.EditorFor(model => model.soluong, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
                @Html.ValidationMessageFor(model => model.soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.idloaisp, "Loại Sản Phẩm", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.DropDownList("tenloaisp", null, htmlAttributes: new { @class = "form-control", @id = "type_product", @name = "type_product" })
                @Html.ValidationMessageFor(model => model.idloaisp, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-submit"><small><i class="fa fa-plus"></i></small> Thêm mới</button>
                <a class="btn btn-warning" href="/Admin/SanPhamAd/Index"><small><i class="fa fa-reply"></i></small> Trở về</a>
            </div>
        </div>
    </div>
}

WebMyPham/WebMyPham/WebMyPham/WebMyPham/Areas/Admin/Views/SanPhamAd/Delete.cshtml
@model WebMyPham.Models.SanPham
@{
    ViewBag.Title = "Xoa san pham";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}


<style>
    .title_dt {
        text-align: center;
        font-size: 20px;
        font-weight: bold;
    }

    .CtSP {
        padding-top: 1.5cm;
        font-weight: bold;
    }

        .CtSP > p {
            padding-left: 2em;
            font-size: 15px;
        }

    .anh {
        margin-left: 3cm;
    }

        .anh img {
            padding-top: 1.5cm;
            width: 100%;
        }
</style>

<br />
<p class="title_dt">Xóa @Model.tensp</p>
<br />
<div class="form-horizontal col-xl-9 col-lg-10 col-md-12 col-sm-12">
    <div class="col-md-4 float-left anh">
        <img src="~/Images/@Model.hinhanh" />
    </div>
    <div class="col-md-6 float-right CtSP">
        <p>Tên Sản Phẩm: @Model.tensp</p>
        <p>Mã Sản Phẩm: @Model.idsp</p>
        
        <p>Giá Sản Phẩm: @Model.giaban.ToString("0,0") VND</p>
        <p>Chi Tiết Sản Phẩm: @Model.mota</p>
        <p>SL Sản Phẩm: @Model.soluong</p>
        <p>Tình Trạng Sản Phẩm: @Model.trangthai</p>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions" style="margin-left: 2em;">
                <input type="submit" value="Xóa Sản Phẩm" class="btn btn-primary" />
                <a class="btn btn-warning" href="/Admin/SanPhamAd/Index"><small><i class="fa fa-reply"></i></small> Trở về</a>
            </div>
        }
    </div>
    <div class="clearfix"></div>
    <br />
</div>

WebMyPham/WebMyPham/WebMyPham/WebMyPham/Areas/Admin/Views/SanPhamAd/Details.cshtml
@model WebMyPham.Models.SanPham
@{
    ViewBag.Title = "Chi tiet san pham";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}
<style>
    .title_dt {
        text-align: center;
        font-size: 20px;
        font-weight: bold;
    }

    .CtSP {
        padding-top: 1.5cm;
        font-weight: bold;
    }

        .CtSP > p {
            padding-left: 2em;
            font-size: 15px;
        }

    .anh {
        margin-left: 3cm;
    }

        .anh img {
            padding-top: 1.5cm;
            width: 100%;
        }
</style>

<br />
<p class="title_dt">Chi Tiết @Model.tensp</p>
<br />
<div class="form-horizontal col-xl-9 col-lg-10 col-md-12 col-sm-12">
    <div class="col-md-4 float-left anh">
        <img src="~/Images/@Model.hinhanh" />
    </div>
    <div class="col-md-6 float-right CtSP">
        <p>Tên Sản Phẩm: @Model.tensp</p>
        <p>Mã Sản Phẩm: @Model.idsp</p>
        <p>Giá Sản Phẩm: @Model.giaban.ToString("0,0") VND</p>
        <p>Chi Tiết Sản Phẩm: @Model.mota</p>
        <p>SL Sản Phẩm: @Model.soluong</p>
        <p>Tình Trạng Sản Phẩm: @Model.trangthai</p>
        <div style="margin-left:2em;">
            <a class="btn btn-primary" href="/Admin/SanPhamAd/Edit/@Model.idsp" data-id="@Model.idsp"<small><i class="fa fa-edit"></i></small>Sửa Thông Tin Sản Phẩm</a>
            <a class="btn btn-warning" href="/Admin/SanPhamAd/Index"><small><i class="fa fa-reply"></i></small> Trở về</a>
        </div>
    </div>
    <div class="clearfix"></div>
    <br />
</div>

WebMyPham/WebMyPham/WebMyPham/WebMyPham/Areas/Admin/Views/SanPhamAd/Edit.cshtml
@model WebMyPham.Models.SanPham
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}
<style>
    p {
        text-align: center;
        font-weight: bold;
        font-size: 20px;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br />
    <p>Sửa Thông Tin Sản Phẩm</p>
    <div class="form-horizontal col-xl-9 col-lg-10 col-md-12 col-sm-12">
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idsp)

        <div class="form-group">
            @Html.LabelFor(model => model.tensp, "Tên Sản Phẩm", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.tensp, new { htmlAttributes = new { @class = "form-control", @name = "title", @type = "text", @value = "", @id = "title", @placeholder = "Tên sản phẩm ( ~ 70 ký tự )", @required = "", @maxlength = "100" } })
                @Html.ValidationMessageFor(model => model.tensp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mota, "Mô Tả", htmlAttributes: new { @class = "col-sm-3 control-label" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.mota, new { htmlAttributes = new { @class = "form-control", @name = "keywords", @type = "text", @value = "", @id = "keywords", @placeholder = "Mô Tả ( ~ 160 ký tự )", @maxlength = "255" } })
                @Html.ValidationMessageFor(model => model.mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinhanh, "Hình Ảnh", htmlAttributes: new { @class = "col-sm-3 control-label" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.hinhanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinhanh, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.giaban, "Giá Sản Phẩm", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.giaban, new { htmlAttributes = new { @class = "form-control", @placeholder = "Giá sản phẩm (đơn vị: VNĐ)", @repuired = "", @maxlength = "255" } })
                @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.trangthai, "Trạng Thái", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.EditorFor(model => model.trangthai, new { htmlAttributes = new { @class = "form-control", @placeholder = "Còn Hàng || Hết Hàng", @required = "" } })
                @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.soluong, "Số Lượng", htmlAttributes: new { @class = "col-sm-3 control-label" })
            <div class="col-sm-2">
                @Html.EditorFor(model => model.soluong, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
                @Html.ValidationMessageFor(model => model.soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.MADM, "Loại Sản Phẩm", htmlAttributes: new { @class = "col-sm-3 control-label required" })
            <div class="col-sm-9">
                @Html.DropDownList("MADM", null, htmlAttributes: new { @class = "form-control", @id = "type_product", @name = "type_product" })
                @Html.ValidationMessageFor(model => model.MADM, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-submit"><small><i class="fa fa-edit"></i></small>Lưu</button>
                <a class="btn btn-warning" href="/Admin/SanPhamAd/Index"><small><i class="fa fa-reply"></i></small> Trở về</a>
            </div>
        </div>
    </div>
}

WebMyPham/WebMyPham/WebMyPham/WebMyPham/Areas/Admin/Views/SanPhamAd/Index.cshtml
@model IEnumerable<WebMyPham.Models.SanPham>
@{
    ViewBag.Title = "Quản trị Sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAD.cshtml";
}
<div id="main">
    <ol class="breadcrumb">
        <li><a href="/Admin/HomeAd/Index"><i class="fa fa-home"></i> Trang quản trị</a></li>
        <li class="active"><a href="/Admin/SanPhamAd/Index"></a></li>
    </ol>
    <div class="col-xs-12">
        <form id="post_form" method="post" action="" role="form">
            <div class="col-xs-12">
                <div class="form-group">
                    <a href="/Admin/SanPhamAd/Create" class="btn btn-submit"><small><i class="fa fa-plus"></i></small> Thêm mới</a>
                    <div class="btn-group pull-right hidden-xs" id="div-search">
                        <input id="search" name="search" type="text" value="" class="form-control" placeholder="Tìm kiếm">
                        <span class="fa fa-search"></span>
                    </div>
                </div>
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th class="hidden-xs">Mã</th>
                            <th>Sản phẩm</th>
                            <th class="hidden-xs" style="text-align:center;">Hình Ảnh</th>
                            @*<th class="hidden-sm hidden-xs" style="text-align: center;">Giá</th>*@
                            @*<th class="hidden-sm hidden-xs">NSD</th>
                            <th class="hidden-sm hidden-xs">Ngày Hot</th>*@
                            <th class="hidden-xs">Giá bán</th>
                            <th>Số lượng</th>
                            <th>TT</th>
                            <th>Trạng Thái</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var sp in Model)
                        {
                            <tr>
                                <td class="hidden-xs">@sp.idsp</td>
                                <td>
                                    <a href="/Admin/SanPhamAd/Details/@sp.idsp">@sp.tensp</a>
                                </td>
                                <td class="hidden-xs" style="text-align:center;">
                                    <img style="height: 30px;" src="~/Images/@sp.hinhanh" />
                                </td>
                                <td class="hidden-sm hidden-xs" style="text-align: center;">@sp.giaban.ToString("0,0")</td>
                                
                                <td class="hidden-xs">@sp.soluong</td>
                                <td>
                                    <a href="/Admin/SanPhamAd/Details/@sp.idsp"><i class="fa fa-info" data-toggle="tooltip" data-placement="top" title="Chi Tiết Sản Phẩm"></i></a>
                                    <a href="/Admin/SanPhamAd/Edit/@sp.idsp"><i class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="Sửa Sản Phẩm"></i></a>
                                    <a href="/Admin/SanPhamAd/Delete/@sp.idsp"><i class="fa fa-trash-o" data-toggle="tooltip" data-placement="top" title="Xóa Sản Phẩm"></i></a>
                                </td>
                                <td>@sp.trangthai</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>